// <auto-generated />
using System;
using LocalizationManager.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalizationManager.DAL.Migrations
{
    [DbContext(typeof(LocalizationDbContext))]
    [Migration("20241118205501_AddedApplicationRegistration")]
    partial class AddedApplicationRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalizationManager.DAL.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "ab",
                            LanguageName = "Abkhazian"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "aa",
                            LanguageName = "Afar"
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "af",
                            LanguageName = "Afrikaans"
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "ak",
                            LanguageName = "Akan"
                        },
                        new
                        {
                            Id = 5,
                            LanguageCode = "sq",
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            Id = 6,
                            LanguageCode = "am",
                            LanguageName = "Amharic"
                        },
                        new
                        {
                            Id = 7,
                            LanguageCode = "ar",
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            Id = 8,
                            LanguageCode = "an",
                            LanguageName = "Aragonese"
                        },
                        new
                        {
                            Id = 9,
                            LanguageCode = "hy",
                            LanguageName = "Armenian"
                        },
                        new
                        {
                            Id = 10,
                            LanguageCode = "as",
                            LanguageName = "Assamese"
                        },
                        new
                        {
                            Id = 11,
                            LanguageCode = "av",
                            LanguageName = "Avaric"
                        },
                        new
                        {
                            Id = 12,
                            LanguageCode = "ae",
                            LanguageName = "Avestan"
                        },
                        new
                        {
                            Id = 13,
                            LanguageCode = "ay",
                            LanguageName = "Aymara"
                        },
                        new
                        {
                            Id = 14,
                            LanguageCode = "az",
                            LanguageName = "Azerbaijani"
                        },
                        new
                        {
                            Id = 15,
                            LanguageCode = "bm",
                            LanguageName = "Bambara"
                        },
                        new
                        {
                            Id = 16,
                            LanguageCode = "ba",
                            LanguageName = "Bashkir"
                        },
                        new
                        {
                            Id = 17,
                            LanguageCode = "eu",
                            LanguageName = "Basque"
                        },
                        new
                        {
                            Id = 18,
                            LanguageCode = "be",
                            LanguageName = "Belarusian"
                        },
                        new
                        {
                            Id = 19,
                            LanguageCode = "bn",
                            LanguageName = "Bengali"
                        },
                        new
                        {
                            Id = 20,
                            LanguageCode = "bi",
                            LanguageName = "Bislama"
                        },
                        new
                        {
                            Id = 21,
                            LanguageCode = "bs",
                            LanguageName = "Bosnian"
                        },
                        new
                        {
                            Id = 22,
                            LanguageCode = "br",
                            LanguageName = "Breton"
                        },
                        new
                        {
                            Id = 23,
                            LanguageCode = "bg",
                            LanguageName = "Bulgarian"
                        },
                        new
                        {
                            Id = 24,
                            LanguageCode = "my",
                            LanguageName = "Burmese"
                        },
                        new
                        {
                            Id = 25,
                            LanguageCode = "ca",
                            LanguageName = "Catalan, Valencian"
                        },
                        new
                        {
                            Id = 26,
                            LanguageCode = "ch",
                            LanguageName = "Chamorro"
                        },
                        new
                        {
                            Id = 27,
                            LanguageCode = "ce",
                            LanguageName = "Chechen"
                        },
                        new
                        {
                            Id = 28,
                            LanguageCode = "ny",
                            LanguageName = "Chichewa, Chewa, Nyanja"
                        },
                        new
                        {
                            Id = 29,
                            LanguageCode = "zh",
                            LanguageName = "Chinese"
                        },
                        new
                        {
                            Id = 30,
                            LanguageCode = "cu",
                            LanguageName = "Church Slavonic, Old Slavonic, Old Church Slavonic"
                        },
                        new
                        {
                            Id = 31,
                            LanguageCode = "cv",
                            LanguageName = "Chuvash"
                        },
                        new
                        {
                            Id = 32,
                            LanguageCode = "kw",
                            LanguageName = "Cornish"
                        },
                        new
                        {
                            Id = 33,
                            LanguageCode = "co",
                            LanguageName = "Corsican"
                        },
                        new
                        {
                            Id = 34,
                            LanguageCode = "cr",
                            LanguageName = "Cree"
                        },
                        new
                        {
                            Id = 35,
                            LanguageCode = "hr",
                            LanguageName = "Croatian"
                        },
                        new
                        {
                            Id = 36,
                            LanguageCode = "cs",
                            LanguageName = "Czech"
                        },
                        new
                        {
                            Id = 37,
                            LanguageCode = "da",
                            LanguageName = "Danish"
                        },
                        new
                        {
                            Id = 38,
                            LanguageCode = "dv",
                            LanguageName = "Divehi, Dhivehi, Maldivian"
                        },
                        new
                        {
                            Id = 39,
                            LanguageCode = "nl",
                            LanguageName = "Dutch, Flemish"
                        },
                        new
                        {
                            Id = 40,
                            LanguageCode = "dz",
                            LanguageName = "Dzongkha"
                        },
                        new
                        {
                            Id = 41,
                            LanguageCode = "en",
                            LanguageName = "English"
                        },
                        new
                        {
                            Id = 42,
                            LanguageCode = "eo",
                            LanguageName = "Esperanto"
                        },
                        new
                        {
                            Id = 43,
                            LanguageCode = "et",
                            LanguageName = "Estonian"
                        },
                        new
                        {
                            Id = 44,
                            LanguageCode = "ee",
                            LanguageName = "Ewe"
                        },
                        new
                        {
                            Id = 45,
                            LanguageCode = "fo",
                            LanguageName = "Faroese"
                        },
                        new
                        {
                            Id = 46,
                            LanguageCode = "fj",
                            LanguageName = "Fijian"
                        },
                        new
                        {
                            Id = 47,
                            LanguageCode = "fi",
                            LanguageName = "Finnish"
                        },
                        new
                        {
                            Id = 48,
                            LanguageCode = "fr",
                            LanguageName = "French"
                        },
                        new
                        {
                            Id = 49,
                            LanguageCode = "fy",
                            LanguageName = "Western Frisian"
                        },
                        new
                        {
                            Id = 50,
                            LanguageCode = "ff",
                            LanguageName = "Fulah"
                        },
                        new
                        {
                            Id = 51,
                            LanguageCode = "gd",
                            LanguageName = "Gaelic, Scottish Gaelic"
                        },
                        new
                        {
                            Id = 52,
                            LanguageCode = "gl",
                            LanguageName = "Galician"
                        },
                        new
                        {
                            Id = 53,
                            LanguageCode = "lg",
                            LanguageName = "Ganda"
                        },
                        new
                        {
                            Id = 54,
                            LanguageCode = "ka",
                            LanguageName = "Georgian"
                        },
                        new
                        {
                            Id = 55,
                            LanguageCode = "de",
                            LanguageName = "German"
                        },
                        new
                        {
                            Id = 56,
                            LanguageCode = "el",
                            LanguageName = "Greek, Modern (1453–)"
                        },
                        new
                        {
                            Id = 57,
                            LanguageCode = "kl",
                            LanguageName = "Kalaallisut, Greenlandic"
                        },
                        new
                        {
                            Id = 58,
                            LanguageCode = "gn",
                            LanguageName = "Guarani"
                        },
                        new
                        {
                            Id = 59,
                            LanguageCode = "gu",
                            LanguageName = "Gujarati"
                        },
                        new
                        {
                            Id = 60,
                            LanguageCode = "ht",
                            LanguageName = "Haitian, Haitian Creole"
                        },
                        new
                        {
                            Id = 61,
                            LanguageCode = "ha",
                            LanguageName = "Hausa"
                        },
                        new
                        {
                            Id = 62,
                            LanguageCode = "he",
                            LanguageName = "Hebrew"
                        },
                        new
                        {
                            Id = 63,
                            LanguageCode = "hz",
                            LanguageName = "Herero"
                        },
                        new
                        {
                            Id = 64,
                            LanguageCode = "hi",
                            LanguageName = "Hindi"
                        },
                        new
                        {
                            Id = 65,
                            LanguageCode = "ho",
                            LanguageName = "Hiri Motu"
                        },
                        new
                        {
                            Id = 66,
                            LanguageCode = "hu",
                            LanguageName = "Hungarian"
                        },
                        new
                        {
                            Id = 67,
                            LanguageCode = "is",
                            LanguageName = "Icelandic"
                        },
                        new
                        {
                            Id = 68,
                            LanguageCode = "io",
                            LanguageName = "Ido"
                        },
                        new
                        {
                            Id = 69,
                            LanguageCode = "ig",
                            LanguageName = "Igbo"
                        },
                        new
                        {
                            Id = 70,
                            LanguageCode = "id",
                            LanguageName = "Indonesian"
                        },
                        new
                        {
                            Id = 71,
                            LanguageCode = "ia",
                            LanguageName = "Interlingua (International Auxiliary Language Association)"
                        },
                        new
                        {
                            Id = 72,
                            LanguageCode = "ie",
                            LanguageName = "Interlingue, Occidental"
                        },
                        new
                        {
                            Id = 73,
                            LanguageCode = "iu",
                            LanguageName = "Inuktitut"
                        },
                        new
                        {
                            Id = 74,
                            LanguageCode = "ik",
                            LanguageName = "Inupiaq"
                        },
                        new
                        {
                            Id = 75,
                            LanguageCode = "ga",
                            LanguageName = "Irish"
                        },
                        new
                        {
                            Id = 76,
                            LanguageCode = "it",
                            LanguageName = "Italian"
                        },
                        new
                        {
                            Id = 77,
                            LanguageCode = "ja",
                            LanguageName = "Japanese"
                        },
                        new
                        {
                            Id = 78,
                            LanguageCode = "jv",
                            LanguageName = "Javanese"
                        },
                        new
                        {
                            Id = 79,
                            LanguageCode = "kn",
                            LanguageName = "Kannada"
                        },
                        new
                        {
                            Id = 80,
                            LanguageCode = "kr",
                            LanguageName = "Kanuri"
                        },
                        new
                        {
                            Id = 81,
                            LanguageCode = "ks",
                            LanguageName = "Kashmiri"
                        },
                        new
                        {
                            Id = 82,
                            LanguageCode = "kk",
                            LanguageName = "Kazakh"
                        },
                        new
                        {
                            Id = 83,
                            LanguageCode = "km",
                            LanguageName = "Central Khmer"
                        },
                        new
                        {
                            Id = 84,
                            LanguageCode = "ki",
                            LanguageName = "Kikuyu, Gikuyu"
                        },
                        new
                        {
                            Id = 85,
                            LanguageCode = "rw",
                            LanguageName = "Kinyarwanda"
                        },
                        new
                        {
                            Id = 86,
                            LanguageCode = "ky",
                            LanguageName = "Kirghiz, Kyrgyz"
                        },
                        new
                        {
                            Id = 87,
                            LanguageCode = "kv",
                            LanguageName = "Komi"
                        },
                        new
                        {
                            Id = 88,
                            LanguageCode = "kg",
                            LanguageName = "Kongo"
                        },
                        new
                        {
                            Id = 89,
                            LanguageCode = "ko",
                            LanguageName = "Korean"
                        },
                        new
                        {
                            Id = 90,
                            LanguageCode = "kj",
                            LanguageName = "Kuanyama, Kwanyama"
                        },
                        new
                        {
                            Id = 91,
                            LanguageCode = "ku",
                            LanguageName = "Kurdish"
                        },
                        new
                        {
                            Id = 92,
                            LanguageCode = "lo",
                            LanguageName = "Lao"
                        },
                        new
                        {
                            Id = 93,
                            LanguageCode = "la",
                            LanguageName = "Latin"
                        },
                        new
                        {
                            Id = 94,
                            LanguageCode = "lv",
                            LanguageName = "Latvian"
                        },
                        new
                        {
                            Id = 95,
                            LanguageCode = "li",
                            LanguageName = "Limburgan, Limburger, Limburgish"
                        },
                        new
                        {
                            Id = 96,
                            LanguageCode = "ln",
                            LanguageName = "Lingala"
                        },
                        new
                        {
                            Id = 97,
                            LanguageCode = "lt",
                            LanguageName = "Lithuanian"
                        },
                        new
                        {
                            Id = 98,
                            LanguageCode = "lu",
                            LanguageName = "Luba-Katanga"
                        },
                        new
                        {
                            Id = 99,
                            LanguageCode = "lb",
                            LanguageName = "Luxembourgish, Letzeburgesch"
                        },
                        new
                        {
                            Id = 100,
                            LanguageCode = "mk",
                            LanguageName = "Macedonian"
                        },
                        new
                        {
                            Id = 101,
                            LanguageCode = "mg",
                            LanguageName = "Malagasy"
                        },
                        new
                        {
                            Id = 102,
                            LanguageCode = "ms",
                            LanguageName = "Malay"
                        },
                        new
                        {
                            Id = 103,
                            LanguageCode = "ml",
                            LanguageName = "Malayalam"
                        },
                        new
                        {
                            Id = 104,
                            LanguageCode = "mt",
                            LanguageName = "Maltese"
                        },
                        new
                        {
                            Id = 105,
                            LanguageCode = "gv",
                            LanguageName = "Manx"
                        },
                        new
                        {
                            Id = 106,
                            LanguageCode = "mi",
                            LanguageName = "Maori"
                        },
                        new
                        {
                            Id = 107,
                            LanguageCode = "mr",
                            LanguageName = "Marathi"
                        },
                        new
                        {
                            Id = 108,
                            LanguageCode = "mh",
                            LanguageName = "Marshallese"
                        },
                        new
                        {
                            Id = 109,
                            LanguageCode = "mn",
                            LanguageName = "Mongolian"
                        },
                        new
                        {
                            Id = 110,
                            LanguageCode = "na",
                            LanguageName = "Nauru"
                        },
                        new
                        {
                            Id = 111,
                            LanguageCode = "nv",
                            LanguageName = "Navajo, Navaho"
                        },
                        new
                        {
                            Id = 112,
                            LanguageCode = "nd",
                            LanguageName = "North Ndebele"
                        },
                        new
                        {
                            Id = 113,
                            LanguageCode = "nr",
                            LanguageName = "South Ndebele"
                        },
                        new
                        {
                            Id = 114,
                            LanguageCode = "ng",
                            LanguageName = "Ndonga"
                        },
                        new
                        {
                            Id = 115,
                            LanguageCode = "ne",
                            LanguageName = "Nepali"
                        },
                        new
                        {
                            Id = 116,
                            LanguageCode = "no",
                            LanguageName = "Norwegian"
                        },
                        new
                        {
                            Id = 117,
                            LanguageCode = "nb",
                            LanguageName = "Norwegian Bokmål"
                        },
                        new
                        {
                            Id = 118,
                            LanguageCode = "nn",
                            LanguageName = "Norwegian Nynorsk"
                        },
                        new
                        {
                            Id = 119,
                            LanguageCode = "oc",
                            LanguageName = "Occitan"
                        },
                        new
                        {
                            Id = 120,
                            LanguageCode = "oj",
                            LanguageName = "Ojibwa"
                        },
                        new
                        {
                            Id = 121,
                            LanguageCode = "or",
                            LanguageName = "Oriya"
                        },
                        new
                        {
                            Id = 122,
                            LanguageCode = "om",
                            LanguageName = "Oromo"
                        },
                        new
                        {
                            Id = 123,
                            LanguageCode = "os",
                            LanguageName = "Ossetian, Ossetic"
                        },
                        new
                        {
                            Id = 124,
                            LanguageCode = "pi",
                            LanguageName = "Pali"
                        },
                        new
                        {
                            Id = 125,
                            LanguageCode = "ps",
                            LanguageName = "Pashto, Pushto"
                        },
                        new
                        {
                            Id = 126,
                            LanguageCode = "fa",
                            LanguageName = "Persian"
                        },
                        new
                        {
                            Id = 127,
                            LanguageCode = "pl",
                            LanguageName = "Polish"
                        },
                        new
                        {
                            Id = 128,
                            LanguageCode = "pt",
                            LanguageName = "Portuguese"
                        },
                        new
                        {
                            Id = 129,
                            LanguageCode = "pa",
                            LanguageName = "Punjabi, Panjabi"
                        },
                        new
                        {
                            Id = 130,
                            LanguageCode = "qu",
                            LanguageName = "Quechua"
                        },
                        new
                        {
                            Id = 131,
                            LanguageCode = "ro",
                            LanguageName = "Romanian, Moldavian, Moldovan"
                        },
                        new
                        {
                            Id = 132,
                            LanguageCode = "rm",
                            LanguageName = "Romansh"
                        },
                        new
                        {
                            Id = 133,
                            LanguageCode = "rn",
                            LanguageName = "Rundi"
                        },
                        new
                        {
                            Id = 134,
                            LanguageCode = "ru",
                            LanguageName = "Russian"
                        },
                        new
                        {
                            Id = 135,
                            LanguageCode = "se",
                            LanguageName = "Northern Sami"
                        },
                        new
                        {
                            Id = 136,
                            LanguageCode = "sm",
                            LanguageName = "Samoan"
                        },
                        new
                        {
                            Id = 137,
                            LanguageCode = "sg",
                            LanguageName = "Sango"
                        },
                        new
                        {
                            Id = 138,
                            LanguageCode = "sa",
                            LanguageName = "Sanskrit"
                        },
                        new
                        {
                            Id = 139,
                            LanguageCode = "sc",
                            LanguageName = "Sardinian"
                        },
                        new
                        {
                            Id = 140,
                            LanguageCode = "sr",
                            LanguageName = "Serbian"
                        },
                        new
                        {
                            Id = 141,
                            LanguageCode = "sn",
                            LanguageName = "Shona"
                        },
                        new
                        {
                            Id = 142,
                            LanguageCode = "sd",
                            LanguageName = "Sindhi"
                        },
                        new
                        {
                            Id = 143,
                            LanguageCode = "si",
                            LanguageName = "Sinhala, Sinhalese"
                        },
                        new
                        {
                            Id = 144,
                            LanguageCode = "sk",
                            LanguageName = "Slovak"
                        },
                        new
                        {
                            Id = 145,
                            LanguageCode = "sl",
                            LanguageName = "Slovenian"
                        },
                        new
                        {
                            Id = 146,
                            LanguageCode = "so",
                            LanguageName = "Somali"
                        },
                        new
                        {
                            Id = 147,
                            LanguageCode = "st",
                            LanguageName = "Southern Sotho"
                        },
                        new
                        {
                            Id = 148,
                            LanguageCode = "es",
                            LanguageName = "Spanish, Castilian"
                        },
                        new
                        {
                            Id = 149,
                            LanguageCode = "su",
                            LanguageName = "Sundanese"
                        },
                        new
                        {
                            Id = 150,
                            LanguageCode = "sw",
                            LanguageName = "Swahili"
                        },
                        new
                        {
                            Id = 151,
                            LanguageCode = "ss",
                            LanguageName = "Swati"
                        },
                        new
                        {
                            Id = 152,
                            LanguageCode = "sv",
                            LanguageName = "Swedish"
                        },
                        new
                        {
                            Id = 153,
                            LanguageCode = "tl",
                            LanguageName = "Tagalog"
                        },
                        new
                        {
                            Id = 154,
                            LanguageCode = "ty",
                            LanguageName = "Tahitian"
                        },
                        new
                        {
                            Id = 155,
                            LanguageCode = "tg",
                            LanguageName = "Tajik"
                        },
                        new
                        {
                            Id = 156,
                            LanguageCode = "ta",
                            LanguageName = "Tamil"
                        },
                        new
                        {
                            Id = 157,
                            LanguageCode = "tt",
                            LanguageName = "Tatar"
                        },
                        new
                        {
                            Id = 158,
                            LanguageCode = "te",
                            LanguageName = "Telugu"
                        },
                        new
                        {
                            Id = 159,
                            LanguageCode = "th",
                            LanguageName = "Thai"
                        },
                        new
                        {
                            Id = 160,
                            LanguageCode = "bo",
                            LanguageName = "Tibetan"
                        },
                        new
                        {
                            Id = 161,
                            LanguageCode = "ti",
                            LanguageName = "Tigrinya"
                        },
                        new
                        {
                            Id = 162,
                            LanguageCode = "to",
                            LanguageName = "Tonga (Tonga Islands)"
                        },
                        new
                        {
                            Id = 163,
                            LanguageCode = "ts",
                            LanguageName = "Tsonga"
                        },
                        new
                        {
                            Id = 164,
                            LanguageCode = "tn",
                            LanguageName = "Tswana"
                        },
                        new
                        {
                            Id = 165,
                            LanguageCode = "tr",
                            LanguageName = "Turkish"
                        },
                        new
                        {
                            Id = 166,
                            LanguageCode = "tk",
                            LanguageName = "Turkmen"
                        },
                        new
                        {
                            Id = 167,
                            LanguageCode = "tw",
                            LanguageName = "Twi"
                        },
                        new
                        {
                            Id = 168,
                            LanguageCode = "ug",
                            LanguageName = "Uighur, Uyghur"
                        },
                        new
                        {
                            Id = 169,
                            LanguageCode = "uk",
                            LanguageName = "Ukrainian"
                        },
                        new
                        {
                            Id = 170,
                            LanguageCode = "ur",
                            LanguageName = "Urdu"
                        },
                        new
                        {
                            Id = 171,
                            LanguageCode = "uz",
                            LanguageName = "Uzbek"
                        },
                        new
                        {
                            Id = 172,
                            LanguageCode = "ve",
                            LanguageName = "Venda"
                        },
                        new
                        {
                            Id = 173,
                            LanguageCode = "vi",
                            LanguageName = "Vietnamese"
                        },
                        new
                        {
                            Id = 174,
                            LanguageCode = "vo",
                            LanguageName = "Volapük"
                        },
                        new
                        {
                            Id = 175,
                            LanguageCode = "wa",
                            LanguageName = "Walloon"
                        },
                        new
                        {
                            Id = 176,
                            LanguageCode = "cy",
                            LanguageName = "Welsh"
                        },
                        new
                        {
                            Id = 177,
                            LanguageCode = "wo",
                            LanguageName = "Wolof"
                        },
                        new
                        {
                            Id = 178,
                            LanguageCode = "xh",
                            LanguageName = "Xhosa"
                        },
                        new
                        {
                            Id = 179,
                            LanguageCode = "ii",
                            LanguageName = "Sichuan Yi, Nuosu"
                        },
                        new
                        {
                            Id = 180,
                            LanguageCode = "yi",
                            LanguageName = "Yiddish"
                        },
                        new
                        {
                            Id = 181,
                            LanguageCode = "yo",
                            LanguageName = "Yoruba"
                        },
                        new
                        {
                            Id = 182,
                            LanguageCode = "za",
                            LanguageName = "Zhuang, Chuang"
                        },
                        new
                        {
                            Id = 183,
                            LanguageCode = "zu",
                            LanguageName = "Zulu"
                        });
                });

            modelBuilder.Entity("LocalizationManager.DAL.Entities.LocalizationValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalizationValues");
                });

            modelBuilder.Entity("LocalizationManager.DAL.Entities.RegisteredApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupportedLanguages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegisteredApplications");
                });

            modelBuilder.Entity("LocalizationManager.DAL.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LocalizationManager.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LocalizationManager.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LocalizationManager.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LocalizationManager.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
