using LocalizationManager.DAL.Entities;
using Microsoft.EntityFrameworkCore;

namespace LocalizationManager.DAL.Seed;

public static class LanguageSeed
{
    public static void SeedLanguages(ModelBuilder modelBuilder)
    {
        List<Language> languages =
        [
            new Language { Id = 1, LanguageName = "Abkhazian", LanguageCode = "ab" },
            new Language { Id = 2, LanguageName = "Afar", LanguageCode = "aa" },
            new Language { Id = 3, LanguageName = "Afrikaans", LanguageCode = "af" },
            new Language { Id = 4, LanguageName = "Akan", LanguageCode = "ak" },
            new Language { Id = 5, LanguageName = "Albanian", LanguageCode = "sq" },
            new Language { Id = 6, LanguageName = "Amharic", LanguageCode = "am" },
            new Language { Id = 7, LanguageName = "Arabic", LanguageCode = "ar" },
            new Language { Id = 8, LanguageName = "Aragonese", LanguageCode = "an" },
            new Language { Id = 9, LanguageName = "Armenian", LanguageCode = "hy" },
            new Language { Id = 10, LanguageName = "Assamese", LanguageCode = "as" },
            new Language { Id = 11, LanguageName = "Avaric", LanguageCode = "av" },
            new Language { Id = 12, LanguageName = "Avestan", LanguageCode = "ae" },
            new Language { Id = 13, LanguageName = "Aymara", LanguageCode = "ay" },
            new Language { Id = 14, LanguageName = "Azerbaijani", LanguageCode = "az" },
            new Language { Id = 15, LanguageName = "Bambara", LanguageCode = "bm" },
            new Language { Id = 16, LanguageName = "Bashkir", LanguageCode = "ba" },
            new Language { Id = 17, LanguageName = "Basque", LanguageCode = "eu" },
            new Language { Id = 18, LanguageName = "Belarusian", LanguageCode = "be" },
            new Language { Id = 19, LanguageName = "Bengali", LanguageCode = "bn" },
            new Language { Id = 20, LanguageName = "Bislama", LanguageCode = "bi" },
            new Language { Id = 21, LanguageName = "Bosnian", LanguageCode = "bs" },
            new Language { Id = 22, LanguageName = "Breton", LanguageCode = "br" },
            new Language { Id = 23, LanguageName = "Bulgarian", LanguageCode = "bg" },
            new Language { Id = 24, LanguageName = "Burmese", LanguageCode = "my" },
            new Language { Id = 25, LanguageName = "Catalan, Valencian", LanguageCode = "ca" },
            new Language { Id = 26, LanguageName = "Chamorro", LanguageCode = "ch" },
            new Language { Id = 27, LanguageName = "Chechen", LanguageCode = "ce" },
            new Language { Id = 28, LanguageName = "Chichewa, Chewa, Nyanja", LanguageCode = "ny" },
            new Language { Id = 29, LanguageName = "Chinese", LanguageCode = "zh" },
            new Language { Id = 30, LanguageName = "Church Slavonic, Old Slavonic, Old Church Slavonic", LanguageCode = "cu" },
            new Language { Id = 31, LanguageName = "Chuvash", LanguageCode = "cv" },
            new Language { Id = 32, LanguageName = "Cornish", LanguageCode = "kw" },
            new Language { Id = 33, LanguageName = "Corsican", LanguageCode = "co" },
            new Language { Id = 34, LanguageName = "Cree", LanguageCode = "cr" },
            new Language { Id = 35, LanguageName = "Croatian", LanguageCode = "hr" },
            new Language { Id = 36, LanguageName = "Czech", LanguageCode = "cs" },
            new Language { Id = 37, LanguageName = "Danish", LanguageCode = "da" },
            new Language { Id = 38, LanguageName = "Divehi, Dhivehi, Maldivian", LanguageCode = "dv" },
            new Language { Id = 39, LanguageName = "Dutch, Flemish", LanguageCode = "nl" },
            new Language { Id = 40, LanguageName = "Dzongkha", LanguageCode = "dz" },
            new Language { Id = 41, LanguageName = "English", LanguageCode = "en" },
            new Language { Id = 42, LanguageName = "Esperanto", LanguageCode = "eo" },
            new Language { Id = 43, LanguageName = "Estonian", LanguageCode = "et" },
            new Language { Id = 44, LanguageName = "Ewe", LanguageCode = "ee" },
            new Language { Id = 45, LanguageName = "Faroese", LanguageCode = "fo" },
            new Language { Id = 46, LanguageName = "Fijian", LanguageCode = "fj" },
            new Language { Id = 47, LanguageName = "Finnish", LanguageCode = "fi" },
            new Language { Id = 48, LanguageName = "French", LanguageCode = "fr" },
            new Language { Id = 49, LanguageName = "Western Frisian", LanguageCode = "fy" },
            new Language { Id = 50, LanguageName = "Fulah", LanguageCode = "ff" },
            new Language { Id = 51, LanguageName = "Gaelic, Scottish Gaelic", LanguageCode = "gd" },
            new Language { Id = 52, LanguageName = "Galician", LanguageCode = "gl" },
            new Language { Id = 53, LanguageName = "Ganda", LanguageCode = "lg" },
            new Language { Id = 54, LanguageName = "Georgian", LanguageCode = "ka" },
            new Language { Id = 55, LanguageName = "German", LanguageCode = "de" },
            new Language { Id = 56, LanguageName = "Greek, Modern (1453–)", LanguageCode = "el" },
            new Language { Id = 57, LanguageName = "Kalaallisut, Greenlandic", LanguageCode = "kl" },
            new Language { Id = 58, LanguageName = "Guarani", LanguageCode = "gn" },
            new Language { Id = 59, LanguageName = "Gujarati", LanguageCode = "gu" },
            new Language { Id = 60, LanguageName = "Haitian, Haitian Creole", LanguageCode = "ht" },
            new Language { Id = 61, LanguageName = "Hausa", LanguageCode = "ha" },
            new Language { Id = 62, LanguageName = "Hebrew", LanguageCode = "he" },
            new Language { Id = 63, LanguageName = "Herero", LanguageCode = "hz" },
            new Language { Id = 64, LanguageName = "Hindi", LanguageCode = "hi" },
            new Language { Id = 65, LanguageName = "Hiri Motu", LanguageCode = "ho" },
            new Language { Id = 66, LanguageName = "Hungarian", LanguageCode = "hu" },
            new Language { Id = 67, LanguageName = "Icelandic", LanguageCode = "is" },
            new Language { Id = 68, LanguageName = "Ido", LanguageCode = "io" },
            new Language { Id = 69, LanguageName = "Igbo", LanguageCode = "ig" },
            new Language { Id = 70, LanguageName = "Indonesian", LanguageCode = "id" },
            new Language { Id = 71, LanguageName = "Interlingua (International Auxiliary Language Association)", LanguageCode = "ia" },
            new Language { Id = 72, LanguageName = "Interlingue, Occidental", LanguageCode = "ie" },
            new Language { Id = 73, LanguageName = "Inuktitut", LanguageCode = "iu" },
            new Language { Id = 74, LanguageName = "Inupiaq", LanguageCode = "ik" },
            new Language { Id = 75, LanguageName = "Irish", LanguageCode = "ga" },
            new Language { Id = 76, LanguageName = "Italian", LanguageCode = "it" },
            new Language { Id = 77, LanguageName = "Japanese", LanguageCode = "ja" },
            new Language { Id = 78, LanguageName = "Javanese", LanguageCode = "jv" },
            new Language { Id = 79, LanguageName = "Kannada", LanguageCode = "kn" },
            new Language { Id = 80, LanguageName = "Kanuri", LanguageCode = "kr" },
            new Language { Id = 81, LanguageName = "Kashmiri", LanguageCode = "ks" },
            new Language { Id = 82, LanguageName = "Kazakh", LanguageCode = "kk" },
            new Language { Id = 83, LanguageName = "Central Khmer", LanguageCode = "km" },
            new Language { Id = 84, LanguageName = "Kikuyu, Gikuyu", LanguageCode = "ki" },
            new Language { Id = 85, LanguageName = "Kinyarwanda", LanguageCode = "rw" },
            new Language { Id = 86, LanguageName = "Kirghiz, Kyrgyz", LanguageCode = "ky" },
            new Language { Id = 87, LanguageName = "Komi", LanguageCode = "kv" },
            new Language { Id = 88, LanguageName = "Kongo", LanguageCode = "kg" },
            new Language { Id = 89, LanguageName = "Korean", LanguageCode = "ko" },
            new Language { Id = 90, LanguageName = "Kuanyama, Kwanyama", LanguageCode = "kj" },
            new Language { Id = 91, LanguageName = "Kurdish", LanguageCode = "ku" },
            new Language { Id = 92, LanguageName = "Lao", LanguageCode = "lo" },
            new Language { Id = 93, LanguageName = "Latin", LanguageCode = "la" },
            new Language { Id = 94, LanguageName = "Latvian", LanguageCode = "lv" },
            new Language { Id = 95, LanguageName = "Limburgan, Limburger, Limburgish", LanguageCode = "li" },
            new Language { Id = 96, LanguageName = "Lingala", LanguageCode = "ln" },
            new Language { Id = 97, LanguageName = "Lithuanian", LanguageCode = "lt" },
            new Language { Id = 98, LanguageName = "Luba-Katanga", LanguageCode = "lu" },
            new Language { Id = 99, LanguageName = "Luxembourgish, Letzeburgesch", LanguageCode = "lb" },
            new Language { Id = 100, LanguageName = "Macedonian", LanguageCode = "mk" },
            new Language { Id = 101, LanguageName = "Malagasy", LanguageCode = "mg" },
            new Language { Id = 102, LanguageName = "Malay", LanguageCode = "ms" },
            new Language { Id = 103, LanguageName = "Malayalam", LanguageCode = "ml" },
            new Language { Id = 104, LanguageName = "Maltese", LanguageCode = "mt" },
            new Language { Id = 105, LanguageName = "Manx", LanguageCode = "gv" },
            new Language { Id = 106, LanguageName = "Maori", LanguageCode = "mi" },
            new Language { Id = 107, LanguageName = "Marathi", LanguageCode = "mr" },
            new Language { Id = 108, LanguageName = "Marshallese", LanguageCode = "mh" },
            new Language { Id = 109, LanguageName = "Mongolian", LanguageCode = "mn" },
            new Language { Id = 110, LanguageName = "Nauru", LanguageCode = "na" },
            new Language { Id = 111, LanguageName = "Navajo, Navaho", LanguageCode = "nv" },
            new Language { Id = 112, LanguageName = "North Ndebele", LanguageCode = "nd" },
            new Language { Id = 113, LanguageName = "South Ndebele", LanguageCode = "nr" },
            new Language { Id = 114, LanguageName = "Ndonga", LanguageCode = "ng" },
            new Language { Id = 115, LanguageName = "Nepali", LanguageCode = "ne" },
            new Language { Id = 116, LanguageName = "Norwegian", LanguageCode = "no" },
            new Language { Id = 117, LanguageName = "Norwegian Bokmål", LanguageCode = "nb" },
            new Language { Id = 118, LanguageName = "Norwegian Nynorsk", LanguageCode = "nn" },
            new Language { Id = 119, LanguageName = "Occitan", LanguageCode = "oc" },
            new Language { Id = 120, LanguageName = "Ojibwa", LanguageCode = "oj" },
            new Language { Id = 121, LanguageName = "Oriya", LanguageCode = "or" },
            new Language { Id = 122, LanguageName = "Oromo", LanguageCode = "om" },
            new Language { Id = 123, LanguageName = "Ossetian, Ossetic", LanguageCode = "os" },
            new Language { Id = 124, LanguageName = "Pali", LanguageCode = "pi" },
            new Language { Id = 125, LanguageName = "Pashto, Pushto", LanguageCode = "ps" },
            new Language { Id = 126, LanguageName = "Persian", LanguageCode = "fa" },
            new Language { Id = 127, LanguageName = "Polish", LanguageCode = "pl" },
            new Language { Id = 128, LanguageName = "Portuguese", LanguageCode = "pt" },
            new Language { Id = 129, LanguageName = "Punjabi, Panjabi", LanguageCode = "pa" },
            new Language { Id = 130, LanguageName = "Quechua", LanguageCode = "qu" },
            new Language { Id = 131, LanguageName = "Romanian, Moldavian, Moldovan", LanguageCode = "ro" },
            new Language { Id = 132, LanguageName = "Romansh", LanguageCode = "rm" },
            new Language { Id = 133, LanguageName = "Rundi", LanguageCode = "rn" },
            new Language { Id = 134, LanguageName = "Russian", LanguageCode = "ru" },
            new Language { Id = 135, LanguageName = "Northern Sami", LanguageCode = "se" },
            new Language { Id = 136, LanguageName = "Samoan", LanguageCode = "sm" },
            new Language { Id = 137, LanguageName = "Sango", LanguageCode = "sg" },
            new Language { Id = 138, LanguageName = "Sanskrit", LanguageCode = "sa" },
            new Language { Id = 139, LanguageName = "Sardinian", LanguageCode = "sc" },
            new Language { Id = 140, LanguageName = "Serbian", LanguageCode = "sr" },
            new Language { Id = 141, LanguageName = "Shona", LanguageCode = "sn" },
            new Language { Id = 142, LanguageName = "Sindhi", LanguageCode = "sd" },
            new Language { Id = 143, LanguageName = "Sinhala, Sinhalese", LanguageCode = "si" },
            new Language { Id = 144, LanguageName = "Slovak", LanguageCode = "sk" },
            new Language { Id = 145, LanguageName = "Slovenian", LanguageCode = "sl" },
            new Language { Id = 146, LanguageName = "Somali", LanguageCode = "so" },
            new Language { Id = 147, LanguageName = "Southern Sotho", LanguageCode = "st" },
            new Language { Id = 148, LanguageName = "Spanish, Castilian", LanguageCode = "es" },
            new Language { Id = 149, LanguageName = "Sundanese", LanguageCode = "su" },
            new Language { Id = 150, LanguageName = "Swahili", LanguageCode = "sw" },
            new Language { Id = 151, LanguageName = "Swati", LanguageCode = "ss" },
            new Language { Id = 152, LanguageName = "Swedish", LanguageCode = "sv" },
            new Language { Id = 153, LanguageName = "Tagalog", LanguageCode = "tl" },
            new Language { Id = 154, LanguageName = "Tahitian", LanguageCode = "ty" },
            new Language { Id = 155, LanguageName = "Tajik", LanguageCode = "tg" },
            new Language { Id = 156, LanguageName = "Tamil", LanguageCode = "ta" },
            new Language { Id = 157, LanguageName = "Tatar", LanguageCode = "tt" },
            new Language { Id = 158, LanguageName = "Telugu", LanguageCode = "te" },
            new Language { Id = 159, LanguageName = "Thai", LanguageCode = "th" },
            new Language { Id = 160, LanguageName = "Tibetan", LanguageCode = "bo" },
            new Language { Id = 161, LanguageName = "Tigrinya", LanguageCode = "ti" },
            new Language { Id = 162, LanguageName = "Tonga (Tonga Islands)", LanguageCode = "to" },
            new Language { Id = 163, LanguageName = "Tsonga", LanguageCode = "ts" },
            new Language { Id = 164, LanguageName = "Tswana", LanguageCode = "tn" },
            new Language { Id = 165, LanguageName = "Turkish", LanguageCode = "tr" },
            new Language { Id = 166, LanguageName = "Turkmen", LanguageCode = "tk" },
            new Language { Id = 167, LanguageName = "Twi", LanguageCode = "tw" },
            new Language { Id = 168, LanguageName = "Uighur, Uyghur", LanguageCode = "ug" },
            new Language { Id = 169, LanguageName = "Ukrainian", LanguageCode = "uk" },
            new Language { Id = 170, LanguageName = "Urdu", LanguageCode = "ur" },
            new Language { Id = 171, LanguageName = "Uzbek", LanguageCode = "uz" },
            new Language { Id = 172, LanguageName = "Venda", LanguageCode = "ve" },
            new Language { Id = 173, LanguageName = "Vietnamese", LanguageCode = "vi" },
            new Language { Id = 174, LanguageName = "Volapük", LanguageCode = "vo" },
            new Language { Id = 175, LanguageName = "Walloon", LanguageCode = "wa" },
            new Language { Id = 176, LanguageName = "Welsh", LanguageCode = "cy" },
            new Language { Id = 177, LanguageName = "Wolof", LanguageCode = "wo" },
            new Language { Id = 178, LanguageName = "Xhosa", LanguageCode = "xh" },
            new Language { Id = 179, LanguageName = "Sichuan Yi, Nuosu", LanguageCode = "ii" },
            new Language { Id = 180, LanguageName = "Yiddish", LanguageCode = "yi" },
            new Language { Id = 181, LanguageName = "Yoruba", LanguageCode = "yo" },
            new Language { Id = 182, LanguageName = "Zhuang, Chuang", LanguageCode = "za" },
            new Language { Id = 183, LanguageName = "Zulu", LanguageCode = "zu" },
        ];

        modelBuilder.Entity<Language>().HasData(languages);
    }
}
